### ISSUE TITLE
Name this Project

### ISSUE THREAD

**Issue by dansackett** [codezeus/calliope#15]
So I don't think it should be django-react-blog forever. I think as we develop it into a real platform, we can name it something much simpler and overall cooler. We can use this thread to express ideas.

**Comment by chrisburnell** [comment]
# Kalliope

Not sure how *cool* this suggestion may be, but it has an apt background; though, I'm not sure how "attractive" it is from a "marketing perspective".

From the two minutes research I did (based around the idea of this being a child of Code**Zeus**), Kalliope was one of [Zeus' nine muses][1], specifically ["the muse who presides over eloquence and epic poetry; so called from the ecstatic harmony of her voice and is believed to be Homer's muse for the Iliad and the Odyssey."][2]

Another question with this one is: **K**alliope or **C**alliope? Calliope seems to be the *Latin* spelling... I'm not even sure. Maybe we just *pick* one? — [http://www.theoi.com/Ouranios/MousaKalliope.html][3]

*sorry for overuse of italics.*

[1]: http://en.wikipedia.org/wiki/Muse
[2]: http://en.wikipedia.org/wiki/Calliope
[3]: http://www.theoi.com/Ouranios/MousaKalliope.html

**Comment by dansackett** [comment]
I forgot to answer this but I love the name. Smart and plays off things well. For some reason I prefer it with the C.
